#!/usr/bin/env python3

import csv
import os
import pprint


CARDINALITY_NAME = {
    "?": "0..1",
    "*": "0..*",
    "1": "1..1",
    "+": "1..*",
}

DATATYPE_NAME = {
    "A": "Amount       ",
    "B": "Binary object",
    "C": "Code         ",
    "D": "Date         ",
    "I": "Identifier   ",
    "P": "Percentage   ",
    "Q": "Quantity     ",
    "T": "Text         ",

    "G": "Group        "
}




# Transate the official semantic name to the form in the KoSIT XML format
def smx_name(official_name: str) -> str:

    # Deal with bug 1 in xrechnung-visualization:
    # <xr:Item_price_base_quantity_unit_of_measure> is used as XML tag for
    # BT-150, but in the XRechnung spec the full name has an additional "_code".
    if official_name == "Item price base quantity unit of measure code":
        official_name = "Item price base quantity unit of measure"

    n = official_name.replace(" ", "_")
    return f"xr:{n}"




def smx2btj_recurse(bgno: str, prefix: str, indent: str, bt, bg) -> str:

    # Deal with bug 2 in xrechnung-visualization:
    # <xr:INVOICING_PERIOD> is a child of <xr:INVOICE> but in the XRechnung
    # spec "INVOICING PERIOD" is a child of "DELIVERY INFORMATION", which is
    # a child of "INVOICE"
    if bgno == "14":
        prefix = smx_name(bg[bgno]['Name']) + "/"

    if bgno == "0":
        head = """<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" 
                xmlns:xr="urn:ce.eu:en16931:2017:xoev-de:kosit:standard:xrechnung-1">

<!-- Generated by gaul/semantic_model/gen.py from bt_semantic_model.csv
     CAUTION: Does not produce valid JSON because of trailing commas in objects.
              Parse result with JSON5 or Hjson or take it as valid YAML. -->

<xsl:import href="../common.xslt" />
<xsl:output method="text" encoding="utf-8" /> 
<xsl:strip-space elements="*" />


<xsl:template match="xr:invoice">
  <xsl:text>{
  "_meta": {
    "format": "XRechnung Business Terms",
    "version": "0.9",
    "description": "XRechnung invoice condensed to business terms and encoded in JSON"
  },
  "invoice": {</xsl:text>"""
        tail = """
  <xsl:text>
  }
}
</xsl:text>
</xsl:template>
</xsl:stylesheet>"""

    elif bg[bgno]['Cardinality'] in ["?", "1"]:

        head = f"""
{indent}  <xsl:variable name="bg-{bgno}">"""
        # test="string($bg-{bgno})" is necessary, see below
        tail = f"""
{indent}  </xsl:variable>
{indent}  <xsl:if test="string($bg-{bgno})">
{indent}    <xsl:text>&#10;{indent}    "BG{bgno.zfill(3)}": {{</xsl:text>
{indent}    <xsl:value-of select="substring($bg-{bgno}, 1, string-length($bg-{bgno}) - 1)" />
{indent}    <xsl:text>&#10;{indent}    }},</xsl:text>
{indent}  </xsl:if>"""
        indent += "  "

    else:
        # Wrap in for-each loop if the group can appear more than once
        #
        # test="string($bg-{bgno})" is required, because an empty for-each loop
        # generates an empty Result Tree Fragment (RTF), that is not false.
        # But when converted to a string this string is empty, which is false.
        head = f"""
{indent}  <xsl:variable name="bg-{bgno}">
{indent}    <xsl:for-each select="{prefix[:-1]}">
{indent}      <xsl:text>&#10;{indent}      {{</xsl:text>"""
        tail = f"""
{indent}      <xsl:text>&#10;{indent}      }},</xsl:text>
{indent}    </xsl:for-each>
{indent}  </xsl:variable>
{indent}  <xsl:if test="string($bg-{bgno})">
{indent}    <xsl:text>&#10;{indent}    "BG{bgno.zfill(3)}": [</xsl:text>
{indent}    <xsl:value-of select="substring($bg-{bgno}, 1, string-length($bg-{bgno}) - 1)" />
{indent}    <xsl:text>&#10;{indent}    ],</xsl:text>
{indent}  </xsl:if>"""
        prefix = ""
        indent += "    "

    r = head
    for i, row in bt.items():
        if row['BG'] == bgno:
            xpath = prefix + smx_name(row['Name'])

            if row['Cardinality'] in ["*", "+"]:
                template_name = "array"
            elif row['Datatype'] == 'B':
                template_name = "binary_object_SMX"
            elif row['Datatype'] == 'D':
                template_name = "date_from_iso8601"
            else:
                template_name = "string"
            r += f"""
{indent}  <xsl:call-template name="{template_name}">
{indent}    <xsl:with-param name="xmltag" select="{xpath}"/>
{indent}    <xsl:with-param name="jsonkey" select="'BT{i.zfill(3)}'"/>
{indent}    <xsl:with-param name="indent" select="'{indent}'"/>
{indent}  </xsl:call-template>"""


    for i, row in bg.items():
        if row['BG'] == bgno:
            r += smx2btj_recurse(i, prefix + smx_name(row['Name']) + "/", 
                                 indent, bt, bg)
    return r + tail + "\n"






def btj2smx_recurse(bgno: str, indent: str, bt, bg) -> str:
    tag = smx_name(bg[bgno]['Name'])
    head = f'{indent}<{tag} xr:id="BG-{bgno}">'
    tail = f"{indent}</{tag}>\n"

    if bgno == "0":
        # special case for root element
        head = '''{{#invoice}}
<xr:invoice xmlns:xr="urn:ce.eu:en16931:2017:xoev-de:kosit:standard:xrechnung-1">'''
        tail = '''</xr:invoice>
{{/invoice}}'''
    else:
        # wrap in for-each loop anyway
        bgtag = f"BG{bgno.zfill(3)}"
        head = f"{indent}{{{{#{bgtag}}}}}\n" + head
        tail = tail + f"{indent}{{{{/{bgtag}}}}}\n"

    indent += "  "
    r = "\n"
    for i, row in bt.items():
        if row['BG'] == bgno:
            xmltag = smx_name(row['Name'])
            bttag = f"BT{i.zfill(3)}"

            if row['Datatype'] == 'B':
                content = f' mime_code="{{{{mime}}}}" filename="{{{{filename}}}}">{{{{base64}}}}'
            elif row['Datatype'] == 'D':
                content = f'>{{{{YYYY}}}}-{{{{MM}}}}-{{{{DD}}}}'
            else:
                content = f'>{{{{.}}}}'

            r += f"""{indent}{{{{#{bttag}}}}}
{indent}<{xmltag} xr:id="BT-{i}"{content}</{xmltag}>
{indent}{{{{/{bttag}}}}}
"""


    # Deal with bug in xrechnung-visualization:
    # <xr:INVOICING_PERIOD> is a child of <xr:INVOICE> but in the XRechnung
    # spec "INVOIING PERIOD" is a child of "DELIVERY INFORMATION", which is
    # a child of "INVOICE"
    #
    # Solution: when in BT-13 recurse only in BT-15 and append BT-14 after the
    #           end tag of BT-13
    #           Cascading tests to avoid empty <xr:DELIVERY_INFORMATION> tag
    if bgno == "13":   # BG-13 DELIVERY_INFORMATION
        bg14 = btj2smx_recurse("14", "  ", bt, bg)  # BG-14 INVOICE_PERIOD
        bg15 = btj2smx_recurse("15", indent, bt, bg) # BG-15 DELIVER_TO_ADDRESS
        bg15 = bg15[15:-15] # remove {{#BG015}} and {{/BG015}}
        return ("""  {{#BG013}}
    {{#BG015}}
  <xr:DELIVERY_INFORMATION xr:id="BG-13">
      {{#BT070}}
    <xr:Deliver_to_party_name xr:id="BT-70">{{.}}</xr:Deliver_to_party_name>
      {{/BT070}}
      {{#BT071}}
    <xr:Deliver_to_location_identifier xr:id="BT-71">{{.}}</xr:Deliver_to_location_identifier>
      {{/BT071}}
      {{#BT072}}
    <xr:Actual_delivery_date xr:id="BT-72">{{YYYY}}-{{MM}}-{{DD}}</xr:Actual_delivery_date>
      {{/BT072}}
""" + bg15 + """  </xr:DELIVERY_INFORMATION>
    {{/BG015}}
    {{^BG015}}
      {{#BT070}}
  <xr:DELIVERY_INFORMATION xr:id="BG-13">
    <xr:Deliver_to_party_name xr:id="BT-70">{{.}}</xr:Deliver_to_party_name>
        {{#BT071}}
    <xr:Deliver_to_location_identifier xr:id="BT-71">{{.}}</xr:Deliver_to_location_identifier>
        {{/BT071}}
        {{#BT072}}
    <xr:Actual_delivery_date xr:id="BT-72">{{YYYY}}-{{MM}}-{{DD}}</xr:Actual_delivery_date>
        {{/BT072}}
  </xr:DELIVERY_INFORMATION>
      {{/BT070}}
      {{^BT070}}
        {{#BT071}}
  <xr:DELIVERY_INFORMATION xr:id="BG-13">
    <xr:Deliver_to_location_identifier xr:id="BT-71">{{.}}</xr:Deliver_to_location_identifier>
          {{#BT072}}
    <xr:Actual_delivery_date xr:id="BT-72">{{YYYY}}-{{MM}}-{{DD}}</xr:Actual_delivery_date>
          {{/BT072}}
  </xr:DELIVERY_INFORMATION>
        {{/BT071}}
        {{^BT071}}
          {{#BT072}}
  <xr:DELIVERY_INFORMATION xr:id="BG-13">
    <xr:Actual_delivery_date xr:id="BT-72">{{YYYY}}-{{MM}}-{{DD}}</xr:Actual_delivery_date>
  </xr:DELIVERY_INFORMATION>
          {{/BT072}}
        {{/BT071}}
      {{/BT070}}
    {{/BG015}}
""" + bg14 + "  {{/BG013}}\n")

    for i, row in bg.items():
        if row['BG'] == bgno:
            r += btj2smx_recurse(i, indent, bt, bg)
    return head + r + tail







def main():

    # ------------------------------------------------------------------
    # step 1: read sematic model and create supporting data structures
    # ------------------------------------------------------------------

    sm_rows = []
    bt = {}
    bg = {'0': {'Terminal': "BG",
                'BT': "0",
                'BG': "X",
                'Cardinality': "1",
                'Datatype': "G",
                'Name': "INVOICE"
               }
         }
    bt2sm = {}

    with open('bt_semantic_model.csv', newline='') as f:
        reader = csv.DictReader(f)

        for row in reader:
            sm_rows.append(row)

            if row['Terminal'] == "BT":
                bt[row['BT']] = row
            else:
                bg[row['BT']] = row

            # create dictonary with BT/BG as key and semantic name as value
            btname = f"{row['Terminal']}{row['BT'].zfill(3)}"
            smname = row['Name'].replace(" ", "_")
            if row['Terminal'] == "BT":
                smname = smname[0].upper() + smname[1:].lower()
            else:
                smname = smname.upper()
            bt2sm[btname] = smname





    # ------------------------------------------------------------------
    # step 2: create templates as strings in memory
    # ------------------------------------------------------------------

    with open("common.xslt", "r") as f:
        import_common = f.read()
    start = import_common.index("<xsl:template") # remove header
    stop = import_common.rindex("</xsl:stylesheet>")
    #import_common = import_common[start:stop].replace("\\", "\\\\")
    import_common = import_common[start:stop]

    with open("gen/import_common", "w") as f:
        f.write(import_common)


    template_smx2btj_xslt = smx2btj_recurse("0", "", "", bt, bg)
    template_smx2btj_xslt.replace('<xsl:import href="common.xslt" />', import_common)

    template_btj2smx_mustache = ('<?xml version="1.0" encoding="UTF-8"?>\n'
        +  btj2smx_recurse("0", "", bt, bg))

    with open("cii2btj.xslt", "r") as f:
        template_cii2btj_xslt = f.read()

    with open("btj2cii.mustache", "r") as f:
        template_btj2cii_mustache = f.read()

    # By r''' the strings become raw strings where backslashes do not escape
    # This is important for the escape-json template in common.xslt
    collection = f"""# Generated by gaul/semantic_model/gen.py

cii2btj_xslt = r'''{template_cii2btj_xslt}'''

smx2btj_xslt = r'''{template_smx2btj_xslt}'''

btj2cii_mustache = r'''{template_btj2cii_mustache}'''

btj2smx_mustache = r'''{template_btj2smx_mustache}'''

replace_bt2sm = {pprint.pformat(bt2sm, indent=4)}
"""


    collection = collection.replace('<xsl:import href="common.xslt" />', import_common)
    collection = collection.replace('<xsl:import href="../common.xslt" />', import_common)




    # ------------------------------------------------------------------
    # step 3: write templates to files
    # ------------------------------------------------------------------

    os.makedirs("gen", exist_ok=True)


    # Markdown table of the business terms
    with open("gen/bt_table.md", "w") as f:
        print("| Name                                            | ID     | Container | Data type | Cardinality |", file=f)
        print("| ----------------------------------------------- | ------ | ----- | ------------- | ---- |", file=f)
        for row in sorted(sm_rows, key=lambda x: x['Name']):
            print(f"| {row['Name'].ljust(47)} "
                  f"| {row['Terminal']}-{row['BT'].ljust(3)} "
                  f"| BG-{row['BG'].ljust(2)} "
                  f"| {DATATYPE_NAME[row['Datatype']]} "
                  f"| {CARDINALITY_NAME[row['Cardinality']]} |", file=f)


    # XSLT script to convert the KoSIT semantic model XML to JSON business terms
    with open("gen/smx2btj.xslt", "w") as f:
        f.write(template_smx2btj_xslt)


    # mustache script to convert JSON business terms to the KoSIT semantic model
    with open("gen/btj2smx.mustache", "w") as f:
        f.write(template_btj2smx_mustache)


    # sed script to replace BT names with names from the semantic model
    with open("gen/btj2smj.sed", "w") as f:
        for btname, smname in bt2sm.items():
            print(f's/"{btname}"/"{smname}"/g', file=f)


    # sed script to replace  names from the semantic model with BT names
    with open("gen/smj2btj.sed", "w") as f:
        for btname, smname in bt2sm.items():
            print(f's/"{smname}"/"{btname}"/g', file=f)


    # python source code file with all the templates
    os.makedirs("../py/src/gaul", exist_ok=True)
    with open("../py/src/gaul/templates.py", "w") as f:
        f.write(collection)




if __name__ == "__main__":
    main()
